project:
  type: website
  output-dir: docs

website:
  site-url: https://valentina-gonzalez.netlify.app
  page-navigation: true
  title: "Valentina Gonzalez Madariaga"
  page-footer:
    left: "&copy; Copyright 2024, Valentina González Madariaga"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: lux
    css: styles.css
    mainfont: "Futura PT"
    link-external-newwindow: true
